# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-03-11 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0008_add_unique_file_metadata'),
        ('addons_metadata', '0008_add_metadata_asset_pool'),
    ]

    operations = [
    ]
