# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-09 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0238_abstractprovider_allow_updates'),
        ('osf', '0215_auto_20211001_0611'),
    ]

    operations = [
    ]
